groups:
    - programmer
    - games
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
        - osxdefaults::terminal_preferences
        - osxdefaults::enable_remote_desktop
        - osxdefaults::add_note_to_loginscreen
        - osxdefaults::finder_set_preferred_view_style
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::check_for_software_updates_daily
        - osxdefaults::disable_auto-correct
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_position_the_dock_on_the_right_side
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::dock_set_magnification_on
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        # - osxdefaults::enable_safari_debug_menu
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::enable_time_machine_on_unsupported_volumes
        - osxdefaults::expand_print_panel_by_default
        - osxdefaults::expand_save_panel_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_show_all_files
        - osxdefaults::finder_show_file_extensions
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::finder_unhide_home
        - osxdefaults::increase_sound_quality_for_bluetooth_headphones
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::restart_automatically_if_the_computer_freezes
        - osxdefaults::save_screenshots_in_png_format
        #- osxdefaults::save_screenshots_to_pictures
        - osxdefaults::save_to_disk_not_to_iCloud_by_default
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::set_screensaver_preferences
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::turn_off_keyboard_illumination_when_computer_is_not_used_for_5_minutes
attributes:
    osxdefaults:
        computername: 3n
        loginmessage: "Speak, friend, and enter."
