attributes:
    homebrewalt:
        cask_apps:
            - antirsi
            - hpuload
            - macbreakz
            - mac-informer
            - brain-workshop
            - battery-guardian
