attributes:
    homebrewalt:
        cask_apps:
            - pastor
            - licensed
            - gpgtools
            - keepassx
            # - dashlane
            # - truecrypt
            - password-practice
