groups:
    - accessability
    - automation
    - calctime
    - communication
    - fileshare
    - fileutil
    - font
    # - games
    - graphics
    - hacks
    - health
    - input
    # - kext
    - menubar
    # - metadata
    - network
    - passwords
    # - phone
    - photography
    - plugin
    - prefs
    - quicklook
    - record
    - retina
    - screen
    - sound
    - study
    - subversive
    - sysinfo
    - textedit
    - tools
    - video
    - viewers
    - web
recipes:
    mac_os_x:
        - osxdefaults::set_terminal_profile
attributes:
    homebrewalt:
        apps:
            - fuck
            - dialog
            - ant
            - node # --without-completion --without-npm
            - direnv
            - ghc
            - x11vnc
            - fzf
            - switchaudio-osx
            - ttyrec
            - calcurse
            - ttytter
            - cowsay
            - libqalculate
            - ack
            - shellcheck
            - aalib
            - abook
            - apple-gcc42
            - asciidoc
            - aspell
            - at-spi2-atk
            - base64
            - bash
            - bash-completion
            - bdw-gc
            - cairo
            # - clojure
            - cmake
            - cmus
            - colormake
            - coreutils
            - cscope
            - ctags
            - d-bus
            - dnsmasq
            - docbook
            - docbook-xsl
            - ezcomponents
            - faac
            - faad2
            - feh
            - ffmpeg
            - pidgin
            - fortune
            - gh
            - ghi
            - ghostscript
            - giblib
            - gist
            - git
            - git-extras
            - git-flow
            - gmime
            - gnu-getopt
            - gnu-sed
            - googlecl
            - growly
            - gst-plugins-base
            - gtk-engines
            - guile
            # - hadoop # req: java
            - httrack
            - hub
            - id3tool
            - imagemagick
            - ios-webkit-debug-proxy
            - irssi
            - json-c
            - keepassc
            - legit
            - leiningen
            - leptonica
            - lesspipe
            - libevent
            - libidn
            - libnet
            - libstfl
            - lynx
            - mackup
            - man2html
            - mercurial
            - mobile-shell
            - mongodb
            - mpg123
            - mplayer
            - mtr
            - multimarkdown
            - mutt
            - mysql
            - namebench
            - newsbeuter
            - nginx
            - ninja
            - nmap
            - notmuch
            - nspr
            - nvm
            - objective-caml
            - openjpeg
            # - osxfuse # kext ban
            - p11-kit
            - pdfgrep
            - php56
            - php56-xdebug
            - php-code-sniffer
            - php-cs-fixer
            - phpdocumentor
            - phpmd
            - pianobar
            - pixman
            - pkg-config
            - plowshare # req: imagemagick
            - pngcrush
            - portaudio
            - pow
            - privoxy
            - pwsafe
            - py2cairo
            - pygobject
            - pygtk
            - python
            - python3
            - ranger
            - recode
            - ruby
            - safe-rm
            - screenbrightness
            - spark
            - spidermonkey
            - swi-prolog
            - swig
            - task
            - tcpdump
            - tesseract
            - texi2html
            - the_silver_searcher
            - tig
            - timedog
            - tmux
            - trash
            - tree
            - urlview
            - vifm
            - vim
            - w3m
            - weechat
            - wget
            - wordnet
            - wxmac
            - xmlto
            - youtube-dl
            - z
            - zlib
            - zsh
    nodejs:
        apps:
            - instant-markdown-d
            - js2coffee
            - gitjk
            - hicat
            - peerflix
            - gitio-cli
            - cipherhub
            - juliangruber/vipe
            - asana-cli
            - bower
            - cat-js
            - coffee-script
            - cordova
            - express
            - forever
            - fuck-you
            - generator-chrome-extension
            - generator-express
            - gh
            - gistup
            - grasp
            - grunt-cli
            - grunt-contrib-compass
            - ios-sim
            - jshint
            # - katon # needs sudo or something
            - learnyounode
            - licenseify
            # - madeye
            - node-inspector
            - nvm
            - pageres
            - phantomjs
            - rainbowify
            - roadmap
            - svgo
            - torrent-mount
            - yo
