attributes:
    homebrewalt:
        cask_apps:
            - nvalt
            - gisto
            - kobito
            - treesheets
            - lightpaper
            - libreoffice
            - littleipsum
            - wordservice
